let list = [
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 180, 
    pokemonType: 'psychic', 
    
    moves: [
      {
        name: 'エナジーミックス',
        description: '自分の山札からエネルギーを1枚選び、自分の「フュージョン」のポケモンにつける。そして山札を切る。',
        damage: 0, 
        requiredEnergy: ['psychic'],
      },
      { 
        name: 'サイコジャンプ',
        description: 'のぞむなら、このポケモンと、ついているすべてのカードを、自分の山札にもどして切る。',
        damage: 70, 
        requiredEnergy: ['psychic','colorless'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040104_P_MIXYUUV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },





  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: false, 
    evlovedFrom: 'ミュウ',
    isPokemonV: true, 
    isPokemonVMax: true,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ミュウ', 
    hp: 310, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'クロスフュージョン',
        description: '自分のベンチの「フュージョン」のポケモンが持っているワザを1つ選び、このワザとして使う。',
        damage: 0, 
        requiredEnergy: ['colorless','colorless'],
      },
      { 
        name: 'ダイミラクル',
        description: 'このワザのダメージは、相手のバトルポケモンにかかっている効果を計算しない。',
        damage: 130, 
        requiredEnergy: ['psychic','psychic'],
      }
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: 0,
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040002_P_MYUUVMAX.jpg',

    location: 'pile',
    // holdingEnergy: [],
    // attackedDamage: 0,
  },
  



  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: true, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'ゲノセクト', 
    hp: 190, 
    pokemonType: 'steel', 
    ability: '自分の番に1回使える。自分の手札の枚数が、自分の場の「フュージョン」のポケモンの数と同じ枚数になるように、山札を引く。',
    moves: [
      {
        name: 'テクノバスター',
        description: '次の自分の番、このポケモンはワザが使えない。',
        damage: 210 ,
        requiredEnergy: ['steel','steel','colorless'],
      },
    ], 
    weakeness: 'fire',
    resistance: 'grass',
    runawayCost: ['colorless','colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040107_P_GENOSEKUTOV.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },



  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
  {
    type: 'pokemon',
    isTane: true, 
    // evlovedFrom: 'ゲノセクト',
    isPokemonV: false, 
    isPokemonVMax: false,
    isPokemonShiny: false, 
    isPokemonFusion: true, 
    name: 'メロエッタ', 
    hp: 90, 
    pokemonType: 'psychic', 
    moves: [
      {
        name: 'メロディアスエコー',
        description: '自分の場のポケモンについている「フュージョンエネルギー」の数×70ダメージ。',
        damage: 70,
        requiredEnergy: ['psychic','colorless'],
      },
    ], 
    weakeness: 'dark',
    resistance: 'fighting',
    runawayCost: ['colorless'],
    src: 'https://www.pokemon-card.com/assets/images/card_images/large/S8/040010_P_MEROETTA.jpg',

    location: 'pile',
    holdingEnergy: [],
    attackedDamage: 0,
  },
]

let finalList = list
for(let i in finalList){
  finalList[i].index = parseInt(i)
}


let mewDeck = finalList

export {mewDeck}